-- 创建 User 使用者表格
CREATE TABLE IF NOT EXISTS User (
    UserID INT PRIMARY KEY AUTO_INCREMENT,
    UserName VARCHAR(255),
    Email VARCHAR(255),
    Password VARCHAR(255),
    Biography TEXT
);

-- 创建 Post 發文表格
CREATE TABLE IF NOT EXISTS Post (
    PostID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT,
    Content TEXT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES User(UserID)
);

-- 创建 Comment 留言表格
CREATE TABLE IF NOT EXISTS Comment (
    CommentID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT,
    PostID INT,
    Content TEXT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES User(UserID),
    FOREIGN KEY (PostID) REFERENCES Post(PostID)
);